"""
Django settings for yourtable project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os
import sys
try:
    # Import python-dotenv dynamically to avoid static import errors in editors
    import importlib
    dotenv = importlib.import_module("dotenv")
    load_dotenv = getattr(dotenv, "load_dotenv")
    _DOTENV_AVAILABLE = callable(load_dotenv)
except Exception:
    _DOTENV_AVAILABLE = False

# If python-dotenv is available, load the .env file at project root for local development
if _DOTENV_AVAILABLE:
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from environment. For local development, set DJANGO_SECRET_KEY in a
# .env file (project root) or in your environment. Falls back to a dev value if unset.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or os.environ.get('SECRET_KEY') or 'dev-fallback-secret'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['.herokuapp.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'cloudinary',
    'bookings',
    'menu',
    'users',
    'reviews',
    'about',

]

SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'yourtable.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Include the project-level `templates/` directory so TemplateView can find home.html
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            # Check project-level templates in `TEMPLATES['DIRS']` first so files
            # in the top-level `templates/` directory override third-party app
            # templates (e.g. django-allauth). Then fall back to app directories.
            'loaders': [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                # Provide MEDIA_URL in templates so media paths render correctly
                'django.template.context_processors.media',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yourtable.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


if os.environ.get('DATABASE_URL'):
    try:
        import dj_database_url

        DATABASES = {
            'default': dj_database_url.parse(os.environ.get('DATABASE_URL'), conn_max_age=600)
        }
    except Exception:
        # dj_database_url not installed or parse failed — fallback to local SQLite.
        # Print a simple warning to stdout so devs see why the fallback happened.
        print('WARNING: dj_database_url not available or DATABASE_URL parse failed; falling back to SQLite')
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ACCOUNT_EMAIL_VERIFICATION = 'none'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# URL prefix for static files
STATIC_URL = '/static/'

# During development, serve the project-level `static/` directory.
# This makes files placed at <project_root>/static/ (for example
# `static/css/base.css`) available at /static/css/base.css in the dev server.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Directory where `collectstatic` will collect static files for production.
# Heroku requires a filesystem path for STATIC_ROOT when running collectstatic.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary / media storage: accept either a single `CLOUDINARY_URL` env var
# or the three-piece vars `CLOUDINARY_CLOUD_NAME`,
# `CLOUDINARY_API_KEY` and `CLOUDINARY_API_SECRET`.
CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL')

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

# If the three-piece vars are not present, try to parse CLOUDINARY_URL.
if not (CLOUDINARY_STORAGE.get('CLOUD_NAME') and CLOUDINARY_STORAGE.get('API_KEY') and CLOUDINARY_STORAGE.get('API_SECRET')) and CLOUDINARY_URL:
    try:
        # Prefer the official parser from the cloudinary package when available.
        from cloudinary.utils import parse_cloudinary_url
        parsed = parse_cloudinary_url(CLOUDINARY_URL)
        # Different cloudinary versions may return a dict or tuple/list.
        if isinstance(parsed, dict):
            CLOUDINARY_STORAGE['CLOUD_NAME'] = CLOUDINARY_STORAGE.get('CLOUD_NAME') or parsed.get('cloud_name')
            CLOUDINARY_STORAGE['API_KEY'] = CLOUDINARY_STORAGE.get('API_KEY') or parsed.get('api_key')
            CLOUDINARY_STORAGE['API_SECRET'] = CLOUDINARY_STORAGE.get('API_SECRET') or parsed.get('api_secret')
        else:
            # parsed may be a tuple: (cloud_name, api_key, api_secret, ...)
            try:
                cloud_name, api_key, api_secret = parsed[0], parsed[1], parsed[2]
                CLOUDINARY_STORAGE['CLOUD_NAME'] = CLOUDINARY_STORAGE.get('CLOUD_NAME') or cloud_name
                CLOUDINARY_STORAGE['API_KEY'] = CLOUDINARY_STORAGE.get('API_KEY') or api_key
                CLOUDINARY_STORAGE['API_SECRET'] = CLOUDINARY_STORAGE.get('API_SECRET') or api_secret
            except Exception:
                pass
    except Exception:
        # Fallback simple parser for URLs like: cloudinary://<API_KEY>:<API_SECRET>@<CLOUD_NAME>
        try:
            if CLOUDINARY_URL.startswith('cloudinary://'):
                core = CLOUDINARY_URL[len('cloudinary://'):]
                creds, cloud = core.split('@', 1)
                key, secret = creds.split(':', 1)
                CLOUDINARY_STORAGE['CLOUD_NAME'] = CLOUDINARY_STORAGE.get('CLOUD_NAME') or cloud
                CLOUDINARY_STORAGE['API_KEY'] = CLOUDINARY_STORAGE.get('API_KEY') or key
                CLOUDINARY_STORAGE['API_SECRET'] = CLOUDINARY_STORAGE.get('API_SECRET') or secret
        except Exception:
            pass

if CLOUDINARY_STORAGE.get('CLOUD_NAME') and CLOUDINARY_STORAGE.get('API_KEY') and CLOUDINARY_STORAGE.get('API_SECRET'):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    # Keep MEDIA_URL simple - cloudinary_storage will handle URL generation
    MEDIA_URL = '/media/'

# Email Configuration
# Use console backend for now (prints to logs) until SMTP is configured
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@yourtable.com')

# To enable real email sending, set these environment variables and uncomment:
# if not DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#     EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
#     EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
#     EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
#     EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
#     EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Using Django's default logging configuration (no custom LOGGING dict).

