# Generated by Django 4.2.25 on 2025-11-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_image'),
        ('reviews', '0002_reviewhistory'),
    ]

    operations = [
    ]
